CREATE TABLE IF NOT EXISTS "USER" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "USER"(id) ON DELETE CASCADE,
  token_hash VARCHAR(64) UNIQUE NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS PERSONNE (
  id_p SERIAL PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  sexe VARCHAR(10) DEFAULT '',
  grade VARCHAR(100) DEFAULT '',
  fonction VARCHAR(100) DEFAULT '',
  adresse TEXT DEFAULT '',
  telephone VARCHAR(30) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS MOBILIER (
  id_m VARCHAR(30) PRIMARY KEY,
  designation VARCHAR(150) NOT NULL,
  nomenclature VARCHAR(150) DEFAULT '',
  espece VARCHAR(100) DEFAULT '',
  pu NUMERIC(12,2),
  provenance VARCHAR(150) DEFAULT '',
  etat VARCHAR(50) DEFAULT '',
  observation TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS CONSOMMABLE (
  ref_c VARCHAR(30) PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  categorie VARCHAR(100) DEFAULT '',
  qte INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS POSSEDER (
  id_p INTEGER NOT NULL REFERENCES PERSONNE(id_p) ON DELETE CASCADE,
  id_m VARCHAR(30) NOT NULL REFERENCES MOBILIER(id_m) ON DELETE CASCADE,
  date_posseder DATE,
  quantite_posseder INTEGER,
  PRIMARY KEY (id_p, id_m)
);

CREATE TABLE IF NOT EXISTS PRENDRE (
  id_p INTEGER NOT NULL REFERENCES PERSONNE(id_p) ON DELETE CASCADE,
  ref_c VARCHAR(30) NOT NULL REFERENCES CONSOMMABLE(ref_c) ON DELETE CASCADE,
  date_prendre DATE,
  quantite_prendre INTEGER,
  PRIMARY KEY (id_p, ref_c)
);

CREATE TABLE IF NOT EXISTS MOUVEMENT (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "USER"(id),
  id_p INTEGER NOT NULL REFERENCES PERSONNE(id_p),
  type_item VARCHAR(20) NOT NULL CHECK (type_item IN ('MOBILIER', 'CONSOMMABLE')),
  item_ref VARCHAR(30) NOT NULL,
  type_mouvement VARCHAR(20) NOT NULL CHECK (type_mouvement IN ('ATTRIBUTION', 'RESTITUTION', 'TRANSFERT')),
  quantite INTEGER NOT NULL,
  date_mouvement TIMESTAMP DEFAULT now(),
  commentaire TEXT
);

CREATE INDEX IF NOT EXISTS idx_mouvement_personne ON MOUVEMENT(id_p, date_mouvement DESC);
CREATE INDEX IF NOT EXISTS idx_mouvement_item ON MOUVEMENT(item_ref, type_item);
