ALTER TABLE MOUVEMENT DROP CONSTRAINT IF EXISTS mouvement_type_mouvement_check;
ALTER TABLE MOUVEMENT ADD CONSTRAINT mouvement_type_mouvement_check
  CHECK (type_mouvement IN ('ATTRIBUTION', 'RESTITUTION', 'TRANSFERT', 'APPROVISIONNEMENT'));
